apiVersion: v1
kind: Service
metadata:
  name: urbind-query-mechanism-backend-service
spec:
  type: ClusterIP
  selector:
    app: urbind-query-mechanism-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
