apiVersion: v1
kind: Service
metadata:
  name: urbind-query-mechanism-frontend-service
spec:
  type: ClusterIP
  selector:
    app: urbind-query-mechanism-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
